#!/usr/bin/env python

ANSI_ESC = '\033'
ANSI_BG_RED = ANSI_ESC + '[41m'
ANSI_BG_WHITE = ANSI_ESC + '[47m'
ANSI_BG_MAGENTA = ANSI_ESC + '[45m'
ANSI_FG_RED = ANSI_ESC + '[31m'
ANSI_FG_CYAN = ANSI_ESC + '[36m'
ANSI_FG_BLUE = ANSI_ESC + '[34m'
ANSI_RESET = ANSI_ESC + '[0m'
ANSI_UP = ANSI_ESC + '[1A'
ANSI_DOWN = ANSI_ESC + '[1B'
